name: Publish to npm on Release

on:
  release:
    types: [created]

jobs:
  env:
    NODE_AUTH_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}

  publish:
    name: Publish npm package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
          scope: '@qws-org'
          always-auth: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name:  Build
        run: pnpm run build

      # Align package.json version with тегом (например "1.2.3")
      - name: Align version with tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          pnpm version --no-git-tag-version "$TAG"

      # Publish to npm
      - name: Publish to npm
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
